//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon_commande
    {
        public int id_bon_commande { get; set; }
        public Nullable<int> id_vehicule { get; set; }
        public Nullable<int> id_commande { get; set; }
    
        public virtual vehicule vehicule { get; set; }
        public virtual commande commande { get; set; }
    }
}
