//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commande()
        {
            this.bon_commande = new HashSet<bon_commande>();
        }
    
        public int id_commande { get; set; }
        public Nullable<System.DateTime> date_rdv { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_mode_paiement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_commande> bon_commande { get; set; }
        public virtual user user { get; set; }
        public virtual status status { get; set; }
        public virtual mode_paiement mode_paiement { get; set; }
    }
}
