//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_CatalogueEntities : DbContext
    {
        public BD_CatalogueEntities()
            : base("name=BD_CatalogueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bon_commande> bon_commande { get; set; }
        public virtual DbSet<carburant> carburants { get; set; }
        public virtual DbSet<commande> commandes { get; set; }
        public virtual DbSet<couleur> couleurs { get; set; }
        public virtual DbSet<etat> etats { get; set; }
        public virtual DbSet<marque> marques { get; set; }
        public virtual DbSet<mode_paiement> mode_paiement { get; set; }
        public virtual DbSet<modele> modeles { get; set; }
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vehicule> vehicules { get; set; }
    }
}
