//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modele()
        {
            this.vehicules = new HashSet<vehicule>();
        }
    
        public int id_modele { get; set; }
        public string nom { get; set; }
        public Nullable<int> id_marque { get; set; }
    
        public virtual marque marque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicule> vehicules { get; set; }
    }
}
