//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.commandes = new HashSet<commande>();
        }

        public user(string Login, string MDP)
        {
            this.commandes = new HashSet<commande>();
        }

        public int id_user { get; set; }

        [DisplayName("Login d'utilisateur")]
        [Required(ErrorMessage = "Ce champs est obligatoire!")]
        public string login { get; set; }
       
        [DisplayName("Mot de passe")]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string motdepasse { get; set; }

        public string permis_conduire { get; set; }

        [DisplayName("Nom d'utilisateur")]
        [Required(ErrorMessage = "Ce champs est obligatoire!")]
        public string nom { get; set; }

        [DisplayName("Prénom d'utilisateur")]
        [Required(ErrorMessage = "Ce champs est obligatoire!")]
        public string prenom { get; set; }

        [DisplayName("Type de client")]
        [Required(ErrorMessage = "Ce champs est obligatoire!")]
        public string type { get; set; }

        [DisplayName("Type de compte")]
        [Required(ErrorMessage = "Ce champs est obligatoire!")]
        public string type_compte { get; set; }

        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande> commandes { get; set; }
    }
}
