//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_KVGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicule()
        {
            this.bon_commande = new HashSet<bon_commande>();
        }
    
        public int id_vehicule { get; set; }
        public string immatriculation { get; set; }
        public Nullable<decimal> prix { get; set; }
        public Nullable<int> kilometrage { get; set; }
        public Nullable<System.DateTime> date_construction { get; set; }
        public Nullable<System.DateTime> date_mise_vente { get; set; }
        public bool est_vendu { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_modele { get; set; }
        public Nullable<int> id_couleur { get; set; }
        public Nullable<int> id_carburant { get; set; }
        public Nullable<int> id_etat { get; set; }
        public byte[] image { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_commande> bon_commande { get; set; }
        public virtual carburant carburant { get; set; }
        public virtual couleur couleur { get; set; }
        public virtual etat etat { get; set; }
        public virtual modele modele { get; set; }
        public virtual type type { get; set; }
    }
}
